/** @generated by scripts/compile-framework-layout.mjs — do not edit */
/**
 * @param {Record<string, unknown>} data
 * @param {Record<string, any>} helpers
 * @returns {string}
 */
export declare function render(data: Record<string, unknown>, helpers: Record<string, any>): string;
